# Étape 1: Build de l'application React
FROM node:18 AS build
WORKDIR /app

# Copier package.json et installer les dépendances
COPY package*.json ./
RUN npm install

# Copier tout le code source et builder l'application
COPY . ./
RUN npm run build

# Étape 2: Servir l'application avec Nginx
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

# Exposer le port par défaut de Nginx
EXPOSE 80

# Lancer Nginx
CMD ["nginx", "-g", "daemon off;"]
