name: Deploy Backend with Quality Checks

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd crmBackend
          npm install

      - name: Run ESLint
        run: |
          cd crmBackend
          npx eslint .

     # - name: Run Unit Tests
      #  run: |
     #     cd crmBackendz
      #    npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./crmBackend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
